version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: h723aHdsa73
    networks: 
      - dbnet
  node:
    image: nodeapp:latest
    build: .
    volumes:
      - .:/var/node-app
      - /var/node-app/node_modules
    networks:
      - dbnet
    ports:
     - 8080:8080
    command: npm run dev
    depends_on:
      - db
networks:
  dbnet: