version: '3.1'

services:
  db:
    image: mongo:4.1-xenial
    restart: always
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: H61ehsaFDsu4
      MONGO_INITDB_DATABASE: quizzless
      MONGO_USER_USERNAME: quizmaster
      MONGO_USER_PASSWORD: asdH2djaSDah3
    networks:
      - dbnet
  node:
    image: nodeapp:latest
    build: .
    volumes:
      - .:/var/node-app
      - /var/node-app/node_modules
    networks:
      - dbnet
    ports:
     - 8080:8080
    command: npm run dev
    depends_on:
      - db
networks:
  dbnet:
