const gameConsts = {
  CREATE: 'ws/GAME_CREATE',
  CREATED: 'ws/GAME_CREATED',

  WIN: 'ws/GAME_WIN',
  LOSS: 'ws/GAME_LOSS',

  VERIFY_ANSWER_REQUEST: 'ws/GAME_VERIFY_ANSWER_REQUEST',
  ANSWER_CORRECT: 'ws/GAME_ANSWER_CORRECT',
  ANSWER_WRONG: 'ws/GAME_ANSWER_WRONG',

  NEXT_QUESTION: 'ws/NEXT_QUESTION'
}

const roomConsts = {
  CREATE: 'ws/ROOM_CREATE',
  REMOVE: 'ws/ROOM_DELETE',

  CREATED: 'ws/ROOM_CREATED',
  REMOVED: 'ws/ROOM_REMOVED',

  USER_CONNECTED: 'ws/ROOM_USER_CONNECTED',
  USER_DISCONNECTED: 'ws/ROOM_USER_DISCONNECTED',

  CONNECTED: 'ws/ROOM_CONNECTED',
  DISCONNECTED: 'ws/ROOM_DISCONNECTED'
}

module.exports = { roomConsts, gameConsts }
