export const alertConsts = {
  SUCCESS: 'ALERT_SUCCESS',
  FAILURE: 'ALERT_FAILURE'
}

export const userConsts = {
  REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
  REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',

  LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

  LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'USER_LOGOUT_FAILURE'
}

export const gameConsts = {
  WIN: 'ws/GAME_WIN',
  LOSS: 'ws/GAME_LOSS',

  VERIFY_ANSWER_REQUEST: 'ws/GAME_VERIFY_ANSWER_REQUEST',
  ANSWER_CORRECT: 'ws/GAME_ANSWER_CORRECT',
  ANSWER_WRONG: 'ws/GAME_ANSWER_WRONG',

  NEXT_QUESTION: 'ws/NEXT_QUESTION'
}

export const roomConsts = {
  CREATE: 'ws/ROOM_CREATE',
  REMOVE: 'ws/ROOM_DELETE',

  CREATED: 'ws/ROOM_CREATED',
  REMOVED: 'ws/ROOM_REMOVED',

  USER_CONNECTED: 'ws/ROOM_USER_CONNECTED',
  USER_DISCONNECTED: 'ws/ROOM_USER_DISCONNECTED',

  CONNECT: 'ROOM_CONNECT',
  DISCONNECT: 'ROOM_DISCONNECT'
}
