export const CREATE_USER = "CREATE_USER"
export const DELETE_USER = "DELETE_USER"
export const UPDATE_USER = "UPDATE_USER"

export const AUTHENTICATE_USER = "AUTHENTICATE_USER"
export const AUTHORIZE_USER = "AUTHORIZE_USER"
export const LOGIN_USER = "LOGIN_USER"
export const LOGOUT_USER = "LOGOUT_USER"

export const GAME_WIN = "GAME_WIN"
export const GAME_LOSS = "GAME_LOSS"
export const INCREMENT_SCORE = "INCREMENT_SCORE"
export const DECREMENT_SCORE = "DECREMENT_SCORE"
export const VERIFY_ANSWER = "VERIFY_ANSWER"

export const CONNECT_TO_ROOM = "CONNECT_TO_ROOM"
export const DISCONNECT_FROM_ROOM = "DISCONNECT_FROM_ROOM"
export const CREATE_ROOM = "CREATE_ROOM"
export const REMOVE_ROOM = "REMOVE_ROOM"